name: "Lee's Place"
favicon: null
layout_spectrum: 0.78738
typography_spectrum: 0.75356
title: "Lee's Place"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d9cbcb'
    - '#c79b39'
    - '#2f2c33'
    - '#69583e'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
