name: "Lee's Place"
favicon: null
layout_spectrum: 0.5008417621720582
typography_spectrum: 0.9187204237096012
title: "Lee's Place"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8449775048065931
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
